server:
  port: 8888
  servlet:
    context-path: /tutuniao

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: tutuniao
    password: tutuniao123!@#123
    url: jdbc:mysql://97.64.36.211/tutuniaoDB?characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true

mybatis:
  type-aliases-package: com.tutuniao.tutuniao.entity
  mapper-locations: classpath:mapper/**/*.xml
